trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

jobs:
- job: 'uwp_32'
  displayName: 'Build all tasks (UWP 32)'
  condition: and(succeeded(), not(variables.task), eq(variables.platform, 'uwp_32'))
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      generator: 'Visual Studio 15 2017'
      platform: 'uwp_32'

- job: 'uwp_64'
  displayName: 'Build all tasks (UWP 64)'
  condition: and(succeeded(), not(variables.task), eq(variables.platform, 'uwp_64'))
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      generator: 'Visual Studio 15 2017 Win64'
      platform: 'uwp_64'

- job: 'uwp_arm'
  displayName: 'Build all tasks (UWP ARM)'
  condition: and(succeeded(), not(variables.task), eq(variables.platform, 'uwp_arm'))
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      generator: 'Visual Studio 15 2017 ARM'
      platform: 'uwp_arm'

- job: 'desktop'
  displayName: 'Build all tasks (Desktop)'
  condition: and(succeeded(), not(variables.task), eq(variables.platform, 'desktop'))
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      generator: 'Visual Studio 15 2017 Win64'
      platform: 'desktop'
