version: 2.1

jobs:
  build:
    docker:
      environment:
          IMAGE_NAME: dynorobotics/balena-amd64-ros2-rcldotnet:dashing
      - image: dynorobotics/balena-amd64-ros2-rcldotnet:dashing
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Build Docker image
        command: |
          docker build -t $IMAGE_NAME .