version: 2

jobs:
  build:
    environment:
        IMAGE_NAME: dynorobotics/balena-amd64-ros2-rcldotnet
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:dashing .

workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: circleci