version: 2

jobs:
  build:
    environment:
        IMAGE_NAME: dynorobotics/balena-amd64-ros2-rcldotnet
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .

  test:
    docker:
      - image: $IMAGE_NAME:latest
    steps:
      - run: source /opt/dotnet_ws/install/setup.sh
      - run:
          name: Change dir to test project
          command: cd /opt/dotnet_ws/src/ros2_dotnet/ros2_dotnet/rcldotnet_tests
      - run: dotnet build
      - run: dotnet test --no-build --logger "trx"
      - run:
          name: test results
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit TestResults/*.trx
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults   
        

workflows:
      version: 2
      main:
        jobs:
          - build:
              filters:
                branches:
                  only: 
                    - dashing
                    - circleci
          - test:
              requires:
                - build
              filters:
                branches:
                  only: 
                    - dashing
                    - circleci