steps:
- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install -U pip setuptools'
  displayName: python -m pip install -U pip setuptools
- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install pyparsing pyyaml'
  displayName: python -m pip install pyparsing pyyaml
- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install EmPy'
  displayName: python -m pip install EmPy
- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install vcstool'
  displayName: python -m pip install vcstool
- task: BatchScript@1
  inputs:
    arguments: '$(Build.SourceBranchName) $(ros2.arch)'
    modifyEnvironment: false
  displayName: Build ROS2 .Net
- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\dev'
    Contents: |
     ament\install\**
     ros2\install\**
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ros2-dotnet-uwp-$(ros2.arch)'
  displayName: Copy ROS2 .Net artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ros2-dotnet-uwp-$(ros2.arch)'
    ArtifactName: 'ros2-dotnet-uwp-$(ros2.arch)'
    publishLocation: Container
  displayName: Publish ROS2 .Net artifacts
